CC=gcc
OBJS=AsciiArtTool.o RLEList.o
EXEC=prog
DEBUG=-g
CFLAGS=-std=c99 -Wall -Werror $(DEBUG)

$(EXEC) : $(OBJS)
	$(CC) $(DEBUG_FLAG) $(OBJS) -o $@

AsciiArtTool.o : AsciiArtTool.c AsciiArtTool.h RLEList.h
RLEList.o : RLEList.c RLEList.h

clean:
	rm -f $(OBJS) $(EXEC)